default_config:
frontend:
mobile_app:
history:
logbook:
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homeassistant:
  packages: !include_dir_named packages
